# Generated by Django 5.1.7 on 2025-04-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_paperpaymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpaymentproof',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
