# Generated by Django 5.1.7 on 2025-04-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_paperpaymentproof_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpaymentproof',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
