# Generated by Django 5.1.7 on 2025-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_paperpaymentproof_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('voucher_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('screenshot', models.FileField(upload_to='proofs/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
