# Generated by Django 5.1.7 on 2025-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_voucherpaymentproof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherpaymentproof',
            name='status',
        ),
        migrations.RemoveField(
            model_name='voucherpaymentproof',
            name='voucher_name',
        ),
        migrations.AddField(
            model_name='voucherpaymentproof',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voucherpaymentproof',
            name='amount',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
