services:
  - type: web
    name: vouchsure
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn vouchsure.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
